# version: '3'
services:
  # postgres database
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust # allow all connections without a password. This is *not* recommended for prod
    volumes:
      - sbac-database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - '5432:5432'
volumes:
  sbac-database-data:
